#! /bin/sh
### BEGIN INIT INFO
# Provides:          telinitq
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: runled daemon for OpenBlockS 600
# Description:       
### END INIT INFO

# Author: Plat'Home <support@plathome.co.jp>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="reload /etc/inittab for openblocks"
NAME=telinitq
SCRIPTNAME=/etc/init.d/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

VERBOSE=yes

#
# Function that starts the daemon/service
#
do_start()
{
	/sbin/telinit q
}

case "$1" in
  start)
	#[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	#do_start
	#case "$?" in
	#	0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	#	2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	#esac
	true
	;;
  stop)
	true
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop}" >&2
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

:
