#! /bin/bash
### BEGIN INIT INFO
# Provides:          nitz
# Required-Start:    $local_fs $syslog $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: get NITZ for OBS IoT
# Description:       
### END INIT INFO
#
# Copyright (c) 2013-2017 Plat'Home CO., LTD.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PLAT'HOME CO., LTD. AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL PLAT'HOME CO., LTD. AND CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin
DESC="get NITZ for obs iot"
NAME=nitz
SCRIPTNAME=/etc/init.d/$NAME
GPIOPATH="/sys/class/gpio"
ATCMD=/usr/sbin/atcmd

# Read configuration variable file if it is present
[ -r /etc/default/openblocks ] && . /etc/default/openblocks

set_time_u200(){
	# check builtin MODEM
	echo -n "nitz: 3G modem power on : "
	$ATCMD PON
	if [ ! -e /dev/ttyACM0 ]; then
		echo "fail"
		exit 1
	fi
	echo "done"

	echo -n "nitz: check SIM card : "
	# check SIM card
	sleep 2
	val=`$ATCMD CCID`
	if [ $? == 255 ]; then
		echo "fail"
		exit 1
	fi
	echo "done"

	echo -n "nitz: time synchronization : "
	val=`$ATCMD CCLK`
	if [ $? == 255 ]; then
		echo "fail"
		exit 1
	fi
	echo "done"

	# set NITZ to SYSTEM
	date "$val"
	# set SYSTEM to RTC
	hwclock --systohc
}

set_time_kym11(){
	echo "done"
}

case "$1" in
  start)
	# initialize LED, INIT
	GPIOPATH="/sys/class/gpio"
	echo 342 > $GPIOPATH/export	# LED red
	[ -d $GPIOPATH/gpio342 ] && echo out > $GPIOPATH/gpio342/direction
	echo 343 > $GPIOPATH/export	# LED green
	[ -d $GPIOPATH/gpio343 ] && echo out > $GPIOPATH/gpio343/direction
	echo 344 > $GPIOPATH/export	# LED blue
	[ -d $GPIOPATH/gpio344 ] && echo out > $GPIOPATH/gpio344/direction
	echo 345 > $GPIOPATH/export	# INIT SW
	[ -d $GPIOPATH/gpio345 ] && echo both > $GPIOPATH/gpio345/edge

	MODEM=`/usr/sbin/obsiot-modem.sh`
	if [ "$MODEM" != "none" ]; then
		obsvx1-modem init
		[ "$MODEM" == "S710" ] && obsvx1-modem power low
		atcmd PON
	fi
	;;
  stop)
	;;
  settime)
	MODEM=`/usr/sbin/obsiot-modem.sh`
	case $MODEM in
	U200*)
		set_time_u200
	;;
	KYM11)
		set_time_kym11
	;;
	*)
	;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|settime}" >&2
	exit 3
	;;
esac

